// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKeFbFxBQ--93RSxrZjYjC9u554ZbLcP0',
    appId: '1:706743386443:web:edaf9bf3bd6f94dd4628ce',
    messagingSenderId: '706743386443',
    projectId: 'deenapp-2e6ff',
    authDomain: 'deenapp-2e6ff.firebaseapp.com',
    storageBucket: 'deenapp-2e6ff.appspot.com',
    measurementId: 'G-X0RFKX4FV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz53HJ9y8znPBGmXlHvb3ic7uIJmr2Mdg',
    appId: '1:706743386443:android:40fcc9b9c03c32204628ce',
    messagingSenderId: '706743386443',
    projectId: 'deenapp-2e6ff',
    storageBucket: 'deenapp-2e6ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlK3kCf-TWlEaFa4PFHncDxQ1vZv80-8k',
    appId: '1:706743386443:ios:09789b2180c132a94628ce',
    messagingSenderId: '706743386443',
    projectId: 'deenapp-2e6ff',
    storageBucket: 'deenapp-2e6ff.appspot.com',
    iosBundleId: 'com.example.deen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlK3kCf-TWlEaFa4PFHncDxQ1vZv80-8k',
    appId: '1:706743386443:ios:e5c0b37a502702c24628ce',
    messagingSenderId: '706743386443',
    projectId: 'deenapp-2e6ff',
    storageBucket: 'deenapp-2e6ff.appspot.com',
    iosBundleId: 'com.example.deen.RunnerTests',
  );
}
